### PR TITLE
Spelling fixes in README

### PR DESCRIPTION
**Pull request by mathias**

### CODE REVIEW

**Comment by maxmunzel** [comment]
Hi Mathias, thanks for the PR! I'd keep "Lamport" uppercased as it is a name (as does Wikipedia). Can you fix it?

**Comment by mathias** [comment]
I believe they’re already upper cased except in the go code sample under “How Syncing Works.” I’ll fix that one.

**Comment by maxmunzel** [comment]
I’ll fix that one.
Hi Mathias, is there another commit coming or should I merge it as-is?

**Comment by mathias** [comment]
The timeline shows it before. https://github.com/maxmunzel/kvass/pull/7/commits/b8bc69c41009943befff33c3066df65a9be08fa4 was the commit.

**Comment by maxmunzel** [comment]
Ah, that’s weird. Anyways thanks for your work! :)

**Pull request merged**
